services:
  mysql:
    image: mysql:8.0
    container_name: bank-db
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=bankdb
      - MYSQL_ROOT_PASSWORD=123